DROP TABLE IF EXISTS REQUEST;

CREATE TABLE REQUEST(FIID INT AUTO_INCREMENT PRIMARY KEY,
					FCIP_ORIGIN VARCHAR(10),
					FDDATE TIMESTAMP NOT NULL,
                    FCMETHOD VARCHAR(250) NOT NULL
);
